[phases.setup]
nixPkgs = ["dotnet-sdk_8", "libicu"]

[phases.install]
cmds = ["dotnet restore --locked-mode"]

[phases.build]
cmds = ["dotnet publish --no-restore -c Release -o out"]

[start]
cmd = "cd out && ASPNETCORE_URLS=http://0.0.0.0:$PORT dotnet ILearn.dll"

[variables]
ChatbotApi__BaseUrl = "http://placeholder:8000"